name: Build MCS OS ISO

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y live-build sudo debootstrap

      - name: Configure and Build ISO
        run: |
          lb config --architecture amd64 --distribution bookworm --archive-areas "main contrib non-free non-free-firmware"
          lb build

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcs-os.iso
          path: "*.iso"
